### ISSUE TITLE
Failing test in acrewriting

### ISSUE THREAD

**Issue by Ari-Zerner** [bytekid/maedmax#2]
The test `check_cps ([g0; g1]) [zero, gzero]` on line 519 of src/rewriting/acrewriting.ml is failing

**Comment by bytekid** [comment]
Thanks for checking carefully!
I investigated and think the computation was correct but the test assertion wrong: while g(0) = 0 is an AC-critical pair (it is also produced by the cps function), it is actually not the only one.
